---
- name: Setup repo GPG keyring
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://download.opensuse.org/repositories/shells:fish/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/fish_shell.gpg

- name: Add debian fish repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/fish_shell.gpg] http://download.opensuse.org/repositories/shells:fish/Debian_11 /
    filename: fish_shell
    state: present

- name: Install fish
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: fish
    state: present

- name: "Set fish as default shell for {{ ansible_user_id }}"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish

- name: "Install Fisher"
  ansible.builtin.shell: |
    /usr/bin/fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'

- name: "Set fisher plugin list"
  ansible.builtin.copy:
    src: fish_plugins
    dest: "{{ ansible_user_dir }}/.config/fish/fish_plugins"

- name: "Install fisher plugins"
  ansible.builtin.shell: |
    /usr/bin/fish -c 'fisher update'
    

- name: Add fish config to ~/.config/fish/config.fish
  ansible.builtin.template:
    src: config.fish.j2
    dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    mode: '0644'
