---
- name: Checkout stacks
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: main
  with_items: "{{ atlas_stacks }}"

- name: Starting stacks
  docker_compose:
    project_src: "{{ item.dest }}"
  with_items: "{{ atlas_stacks }}"
