---
- name: Install required packages
  become: true
  apt:
    name: samba
    state: present

- name: Setup share folder
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items: "{{ samba_shares }}"

- name: Add samba config to /etc/samba/smb.conf
  become: true
  template:
    src:  smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: 'testparm -s %s'
  notify:
    - restart_samba_services