---
atlas_stacks:
  - repo: git@gitlab.com:atlas-container-stacks/portainer.git
    dest: "{{ ansible_user_dir }}/src/atlas-container-stacks/portainer"

  - repo: git@gitlab.com:atlas-container-stacks/luthor.git
    dest: "{{ ansible_user_dir }}/src/atlas-container-stacks/luthor"

  - repo: git@gitlab.com:atlas-container-stacks/nginx.git
    dest: "{{ ansible_user_dir }}/src/atlas-container-stacks/nginx"

  - repo: git@gitlab.com:atlas-container-stacks/pihole.git
    dest: "{{ ansible_user_dir }}/src/atlas-container-stacks/pihole"
