---
- name: restart_docker_service
  become: true
  service:
    name: docker
    state: restarted

- name: reload_docker_service
  become: true
  ansible.builtin.service:
    name: docker
    state: reloaded
