---
- name: Checkout portainer stack
  git:
    repo: https://gitlab.com/atlas-container-stacks/portainer.git
    dest: "{{ ansible_user_dir }}/repos/portainer"

- name: Start portainer stack
  docker_compose:
    project_src: "{{ ansible_user_dir }}/repos/portainer"
  register: portainer_stack_output

- name: Portainer stack creation output
  debug:
    var: portainer_stack_output