---
- name: Create portainer data volume
  docker_volume:
    name: portainer_data

- name: Deploy portainer on 9443
  docker_container:
    image: portainer/portainer-ce:latest
    name: portainer
    state: started
    restart_policy: always
    published_ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data