---
- name: Check if docker is installed
  ansible.builtin.command: which docker
  register: docker_installed
  changed_when: false
  failed_when: false

- name: Install docker
  ansible.builtin.shell: curl -sSL https://get.docker.com | sh
  when: docker_installed.rc == 1

- name: Check docker services status
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install docker python module
  pip:
    name:
      - docker
      - docker-compose
    state: latest

- name: "Add {{ ansible_user_id }} to docker group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Reset ansible connection
  ansible.builtin.meta: reset_connection

# todo: cgroup_enable=memory cgroup_memory=1 shoul be added to /boot/cmdline.txt to enable memory monitoring