---
- name: Check if docker is installed
  command: docker --version
  register: docker_installed
  changed_when: false
  failed_when: false

- name: Install docker
  shell: curl -sSL https://get.docker.com | sh
  when: docker_installed.failed

- name: Check docker services status
  service:
    name: docker
    state: started
    enabled: true

- name: Install docker python module
  pip:
    name: docker
    state: latest

- name: "Add {{ ansible_user_id }} to docker group"
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Reset ansible connection
  meta: reset_connection